[build]
  command = "npm run build"
  publish = "dist"
  directory = "netlify/functions"

# Pour React Router (si jamais tu en utilises un)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

